FROM scalabase as backend-step1-scala

FROM backend-step1-scala AS backend-step2-build
WORKDIR /backend
COPY backend .

FROM backend-step2-build AS backend-step3-rebuild
WORKDIR /backend
COPY backend .
RUN sbt compile
